package com.walkersmithtech.artisonfirst.constant;

public enum RelationshipRole
{
	PERSON_LOCATION,
	PERSON_IMAGE,
	PERSON_COMPANY,
	PROFILE_IMAGE,
	COMPANY_LOCATION,
	COMPANY_IMAGE,
	COMPANY_LOGO,
	COMPANY_PRODUCT,
	COMPANY_PRODUCT_FIELDS,
	PRODUCT_FIELD_VALUE,
	TEAM_MEMBER,
	;
}
